[workspace]
members = ["host", "methods"]
resolver = "2"

[workspace.dependencies]

risc0-zkvm = { version = "2.0.2" }
risc0-steel = { git = "https://github.com/risc0/risc0-ethereum", tag = "v2.0.2" }
